### ISSUE TITLE
[Proposal/Tracker] Add common asked questions in the webpage

### ISSUE THREAD

**Issue by Soremwar** [denoland/deno_website2#439]
I could talk about answering the same questions every 5 minutes in the discord server XD, but i'll just do this

This issue is a tracker _(if this change is approved)_ for a common asked questions section in the website that compiles the conversations around the module system and all sort of controversy topics that people often ask.

Not sure if its @lucacasonato or @ry the one to give a thumbs up to this kind of ideas, but if an agreement is reached about this please write it here and i'll start working on this right away

Extract of answers: 

- [ ] Node vs Deno (Dependency management, JavaScript compatibility, etc) https://github.com/denoland/deno/issues/11
- [ ] Maybe need a package management tool (self explainatory) https://github.com/denoland/deno/issues/47
- [ ] "deno compile" into executable https://github.com/denoland/deno/issues/986
- [ ] Compatibility with node/node modules
- [ ] More to come...

### Disclaimer
This PR compiles the answers to the most asked questions from the people new to the project based on the comentaries given by the mantainers and the community in the issues listed above. Is meant to be an all in one resource to redirect people to when this questions are asked

**Comment by lucacasonato** [comment]
I think we have come to the conclusion that this should be part of the manual. Ref https://github.com/denoland/deno/issues/6844
